from django.urls import path, include
from . import views
urlpatterns = [
path('index', views.index),
path('login', views.login),
path('join', views.join),
path('board', views.board),
path('write', views.write),
path('boardview', views.boardview),
path('intro', views.intro),
path('word', views.word),
path('Idiomatic', views.Idiomatic),
path('Proverb', views. Proverb),
path('Abbreviation', views.Abbreviation),
path('Idiom', views.Idiom),
path('A2', views.A2),
path('I2', views.I2),
path('Id2', views.Id2),
path('Id3', views.Id3),
path('W2', views.W2),
path('W3', views.W3),
path('W4', views.W4),
path('W5', views.W5),
path('W6', views.W6),
path('W7', views.W7),
]
